Support in-commit timestamps in Change Data Feed
delta-io/delta-kernel-rs pull request #581
Opened 2024-12-09 23:46 UTC by OussamaSaoudi-db

## What changes are proposed in this pull request?
This PR adds support for in-commit timestamps in change data feed. We update the `PreparePhaseVisitor` to read `CommitInfo` and extract the timestamp if it is present.

## How was this change tested?
We check that:
- For a table with `CommitInfo`, the timestamp we extract must match the CommitInfo.
- The CommitInfo must be ignored when generating `TableChangesScanData`.

2024-12-10 15:23 UTC, scovich requested changes
Approach looks good, but we're using the wrong column name.

2024-12-30 22:42 UTC, OussamaSaoudi-db commented on kernel/src/transaction.rs
> +    commit_info_data_type
@zachschuermann  just flagging this comment and approach to writing ICT.

2024-12-30 22:43 UTC, OussamaSaoudi-db commented
@scovich This PR has been updated to only add the ICT field to CommitInfo.

2025-01-06 17:24 UTC, scovich approved these changes
LGTM!

2025-01-09 15:32 UTC, zachschuermann approved these changes
LGTM thanks! just a couple quick things

2025-01-09 15:32 UTC, zachschuermann commented on kernel/src/actions/mod.rs
> +    pub(crate) in_commit_timestamp: Option<i64>,
maybe also note that (when enabled) it requires that `commitInfo` be the first action in the commit?

2025-01-09 15:32 UTC, zachschuermann commented on kernel/src/transaction.rs
> +    commit_info_data_type
seems fine :) can we add an issue link/todo so we are tracking this?

2025-01-09 17:42 UTC, OussamaSaoudi-db commented on kernel/src/actions/mod.rs
> +    pub(crate) in_commit_timestamp: Option<i64>,
While that's technically what [the protocol says](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#writer-requirements-for-in-commit-timestamps), delta-spark doesn't check that this is true. It simply [extracts the CommitInfo](https://github.com/delta-io/delta/blob/master/spark/src/main/scala/org/apache/spark/sql/delta/commands/cdc/CDCReader.scala#L628) if present.

I think the error handling would be more code and let us capture fewer tables than delta spark, and commitInfo being the first action doesn't seem to impact us much in this scenario.

2025-01-09 18:50 UTC, scovich commented on kernel/src/actions/mod.rs
> +    pub(crate) in_commit_timestamp: Option<i64>,
Delta-spark doesn't check, but it also does stop looking after the first line of json. So if the commit info is not first it will appear to not exist at all. Sometimes that causes an error, sometimes it would cause a silent wrong behavior.

I would prefer to check strictly unless/until we see a need to do otherwise.

2025-01-09 23:43 UTC, OussamaSaoudi-db commented
@zachschuermann  Added issue here #634

2025-01-09 23:59 UTC, OussamaSaoudi-db commented on kernel/src/actions/mod.rs
> +    pub(crate) in_commit_timestamp: Option<i64>,
@scovich  Do you recommend that we error, or just ignore the ICT

2025-01-15 00:49 UTC, merged