ci: use official action to setup rust toolchain
delta-io/delta-kernel-rs pull request #585
Opened 2024-12-10 15:03 UTC by roeap

## What changes are proposed in this pull request?

The `actions-rs/toolchain` action is deprecated in favor of `actions-rust-lang/setup-rust-toolchain`. This PR updates the usages of the respective actions in the github workflows. THe new action already includes an integration with the rust-cache action, so no need to set that up separately anymore.

This also sets up a dependabot configuration for `cargo` and `github-actions` which we may or may not choose to keep. 

## How was this change tested?

no code changes.

2024-12-10 15:09 UTC, roeap commented on kernel/src/engine/arrow_data.rs
This was my auto-formatter in the IDE, since there are `cargo fmt` checks in ci, nut sure why that happened. In most cases I do like the prior formatting better though, do we a have some line-length config somewhere I am not picking up?

2024-12-10 16:51 UTC, zachschuermann reviewed
nice thanks! changes to existing CI LGTM, just a question on adding dependabot and also overall question: it looks like the two most popular rust toolchains in CI are [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain) and [actions-rust-lang/setup-rust-toolchain](https://github.com/actions-rust-lang/setup-rust-toolchain) with the latter saying that it was heavily inspired by dtolnay's? I guess this has caching built-in as the main benefit?

2024-12-10 16:51 UTC, zachschuermann commented on kernel/src/engine/arrow_data.rs
hm that's interesting - guessing your editor is applying something 'extra' on top of rustfmt? I do prefer the old formatting, can we revert these changes?

2024-12-10 16:51 UTC, zachschuermann commented on .github/dependabot.yaml
oh nice! are we planning on enabling dependabot for the repo?

2024-12-10 16:55 UTC, zachschuermann commented
just want to make sure: is the caching working? I see the following errors in test (ubuntu-latest) in the post-run step:
```
Error: ENOENT: no such file or directory, opendir '/home/runner/work/delta-kernel-rs/delta-kernel-rs/target/tests/target'
Error: Error: ENOENT: no such file or directory, opendir '/home/runner/work/delta-kernel-rs/delta-kernel-rs/target/tests/target'
... Cleaning cargo registry (cache-all-crates: false) ...
... Cleaning cargo/bin ...
... Cleaning cargo git cache ...
... Saving cache ...
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/delta-kernel-rs/delta-kernel-rs --files-from manifest.txt --use-compress-program zstdmt
Failed to save: Unable to reserve cache with key v0-rust-test-64e5ee6e-0ce599cb, another job may be creating this cache. More details: Cache already exists. Scope: refs/pull/585/merge, Key: v0-rust-test-64e5ee6e-0ce599cb, Version: 0d[39](https://github.com/delta-io/delta-kernel-rs/actions/runs/12258931755/job/34199879152#step:7:40)aea52349942f5791850f64e514ac9b6831c456410ea5407f320467a8948d
```

2024-12-10 17:49 UTC, zachschuermann commented on .github/dependabot.yaml
yea I think it is helpful insofar as it just automatically opens small PRs to bump versions and we may (probably) have to manually help upgrade but the 'reminder' to upgrade seems useful? curious to hear what others think

2024-12-11 01:52 UTC, nicklan requested changes
looks good for the runner changes. not as sure about dependabot :)

2024-12-11 01:52 UTC, nicklan commented on .github/workflows/build.yml
> +          cmake-version: "3.30.x"
In yaml double quotes allow escapes and other things, so I tend to prefer single quotes unless I need that, as, fewer surprises. Any reason you changed this?

2024-12-11 01:52 UTC, nicklan commented on .github/dependabot.yaml
> +# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
This link doesn't seem to work. it just goes to a generic support page

2024-12-11 01:52 UTC, nicklan commented on .github/dependabot.yaml
the [dependabot-quickstart-guide](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide) doesn't recommend setting up manually like this, but rather suggests going into settings and letting github create this file. Wondering if we should just do it that way?

2024-12-11 01:52 UTC, nicklan commented on .github/dependabot.yaml
I'm okay trying this out, but also a bit skeptical of the utility here. As far as I can tell it only runs `cargo update`. Generally with how we've set up our `Cargo.toml` this will only do minor updates (i.e. it'll never update arrow 53->54). Maybe that's good, but we need a process to _also_ run `cargo outdated` and try and stay on top of more major updates as well, so I'm not sure how much time this saves us.

2024-12-17 21:57 UTC, zachschuermann approved these changes
LGTM long as all the caching still works :)

2024-12-17 21:57 UTC, zachschuermann commented on .github/workflows/build.yml
>        - name: Install minimal stable with clippy and rustfmt
nit
```suggestion
      - name: Install minimal stable with rustfmt
```

2024-12-17 21:57 UTC, zachschuermann commented on .github/workflows/build.yml
>        - name: Install minimal stable with clippy and rustfmt
nit
```suggestion
      - name: Install minimal stable with clippy
```

2024-12-17 21:57 UTC, zachschuermann commented on .github/workflows/build.yml
> +          cmake-version: "3.30.x"
```suggestion
          cmake-version: '3.30.x'
```

2025-03-19 16:47 UTC, roeap commented
actions now show

```sh
... Restoring cache ...
Cache hit for: v0-rust-test-Linux-x64-f47faad6-dc67ccb0
Received 209715200 of 500222278 (41.9%), 199.4 MBs/sec
Received 496027974 of 500222278 (99.2%), 235.8 MBs/sec
Received 500222278 of 500222278 (100.0%), 229.7 MBs/sec
Cache Size: ~477 MB (500222278 B)
```

so i am reasonably confident the caching still works.

2025-03-19 17:03 UTC, nicklan approved these changes
thanks!

2025-03-19 17:03 UTC, nicklan commented on .github/workflows/build.yml
> +          cmake-version: "3.30.x"
Okay sg. Maybe change back before merge, but not a big deal.

2025-03-19 17:23 UTC, roeap commented on .github/workflows/build.yml
> +          cmake-version: "3.30.x"
```suggestion
          cmake-version: '3.30.x'
```

2025-03-19 17:31 UTC, merged